baseURL = "http://example.org/"
languageCode = "en-us"
theme = "ananke"
title = "Oceanic"

[menu]

[[menu.main]]
    identifier = "home"
    name = "home"
    title = "home"
    url = "/home/"
    weight = -110
