baseURL = "http://example.org/"
languageCode = "en-us"
theme = "ananke"
title = "Oceanic"
[[menu.main]]
name = "Posts"
url = "/posts/"
weight = 2
[[menu.main]]
identifier = "home"
name = "home"
title = "home"
url = "/home/"
weight = 1
